### ISSUE TITLE
ContentDialog showing VM name rather than view?

### ISSUE THREAD

**Issue by Ricent82** [mysteryx93/HanumanInstitute.MvvmDialogs#27] opened 2023-12-15 17:46 UTC
I'm having a bit of trouble getting dialogs to work with FluentAvalonia. I've essentially copied the TextBoxView example from Demo.FluentContentDialog - i.e. my intent is to get this:

![2023-12-15 09 42 45](https://github.com/mysteryx93/HanumanInstitute.MvvmDialogs/assets/73326913/9dad79f9-d413-45b0-9c29-9171c9031b04)

However, I just end up with the content showing the name of the ViewModel, rather than its associated view:

![2023-12-15 09 44 27](https://github.com/mysteryx93/HanumanInstitute.MvvmDialogs/assets/73326913/80de06a8-5495-450e-8475-2effb0e10fd8)

Obviously I'm missing something simple, but I've checked all references of the associated types in my project vs the sample project, and cannot find any difference. Any thoughts about what the issue might be would be greatly appreciated.

**Comment by mysteryx93** [comment] 2023-12-28 17:50
The ViewLocator is responsible for binding the ViewModel type to the View.

For Avalonia projects, the ViewLocator class has double-usage: for Avalonia View lookup like this, and for MvvmDialogs lookups. The suggested implementation supports both at the same time; but it's good to be aware that it's 2 separate use-cases.

**Comment by Ricent82** [comment] 2023-12-29 18:37
Thanks - I'm still unsure how to resolve it though. I've tried explicitly registering with a StrongViewLocator:

```
var build = Locator.CurrentMutable;
build.RegisterLazySingleton(() => (IDialogService)new DialogService(
    new DialogManager(
        new StrongViewLocator()
        .Register<MainViewModel, MainView, MainWindow>()
        .Register<TextPromptViewModel, TextPromptView, TextPromptWindow>(),
dialogFactory: new DialogFactory().AddMessageBox().AddFluent(FluentMessageBoxType.ContentDialog)),
    viewModelFactory: x => Locator.Current.GetService(x)));
```
And I still get the situation noted above. Likewise, I've tried using a custom ViewLocator:
```
var build = Locator.CurrentMutable;
build.RegisterLazySingleton(() => (IDialogService)new DialogService(
    new DialogManager(
        viewLocator: new MyViewLocator(),
        dialogFactory: new DialogFactory().AddMessageBox().AddFluent(FluentMessageBoxType.ContentDialog)),
    viewModelFactory: x => Locator.Current.GetService(x)));
```

...Just so I could set a breakpoint & see how it's being resolved:

```
public class MyViewLocator : ViewLocatorBase
{
    protected override string GetViewName(object viewModel)
    {
        var view = base.GetViewName(viewModel);
        
        // Breakpoint here
        return view;
    }
}
```

But I hit the beakpoint for the MainViewModel, never for the TextPromptViewModel.

**Comment by mysteryx93** [comment] 2023-12-30 22:12
The problem is that you're registering your types only for the ViewLocator used by MvvmDialogs; and that is not the same Locator used by Avalonia!

    <Application.DataTemplates>
        <fluentContentDialog:ViewLocator/>
    </Application.DataTemplates>

Oooohhhhh

This will actually create a 2nd instance of it. This means the registrations must be done inside the ViewLocator constructor and it will be initiated twice. My bad.

Updating FluentContentDialog sample to work with a `StrongViewLocator`; and rewriting StrongViewLocator code and documentation accordingly.

**Closed as completed by mysteryx93** 2023-12-30 22:12 UTC

**Comment by Ricent82** [comment] 2023-12-30 22:21
Sounds good, thanks!

**Comment by JGKle** [comment] 2025-09-03 04:46
I was having this issue too, the problem being that I was missing Application.DataTemplates (until I found this thread) - seems like that's missing in the main ReadMe?

```
<Application.DataTemplates>
    <fluentContentDialog:ViewLocator/>
</Application.DataTemplates>
```
